service: lambda-tokyo 

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
  deploymentBucket: test-dev-lambda
  logRetentionInDays: 30

plugins:
 - serverless-plugin-existing-s3

functions:
  test-sync-s3:
    handler: index.handler
    name:  ${self:provider.stage}-sync-s3
    description:  sync tokyo s3 bucket to another region s3 bucket
    memorySize: 512
    timeout: 180
    reservedConcurrency: 1
    # plugins:
    #   - serverless-plugin-existing-s3
    # package:
    #   include:
    #     - ./index.js
    role: arn:aws:iam::<id>:role/lambdaExec-SSMRead
    events:
      - existingS3:
          bucket: first-lambda-test-s3
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: sync-dir
#     - existingS3:
#           bucket: first-lambda-test-s3
#           events:
#             - s3:ObjectCreated:*
#           rules:
#             - prefix: sync-dir
